# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 78d92bbf2b7c0f5d04310208c2762d93fe268adc93731f0f25c60c0ae8235bc150dfb72ba947273df19270b865a39ff3e427720427eae6da982f3740829a44e9

test:
  secret_key_base: 0468808e5cc82ae1d6855c0aa93b4926f1b15706d090a8d594a6059a3a9e3cc5e00abb25c11c198d64f731cef1b7346f37e9a8624345267f604c40c754b4d116

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
